# Generated by Django 2.2.3 on 2019-08-30 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190830_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='materials',
            field=models.ManyToManyField(related_name='tags', to='core.Material'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='core.Recipe'),
        ),
    ]
