# Generated by Django 2.2.3 on 2019-08-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_tag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='prohibitions',
            field=models.ManyToManyField(null=True, related_name='blockers', to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='category',
            name='requirements',
            field=models.ManyToManyField(null=True, related_name='categories', to='core.Tag'),
        ),
    ]
