# Generated by Django 2.2.3 on 2019-08-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190830_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='benefit',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='prohibitions',
            field=models.ManyToManyField(blank=True, related_name='blockers', to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='category',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='categories', to='core.Tag'),
        ),
    ]
