# Generated by Django 2.2.3 on 2019-08-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_searchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='count',
        ),
    ]
