# Generated by Django 2.2.3 on 2019-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_searchhistory_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nutrition',
            field=models.TextField(blank=True, default=''),
        ),
    ]
