# Generated by Django 2.2.3 on 2019-08-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recipe_nutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
